iamgoodbytes/2imd-webtechadvanced-labs

- madina_jurakholova.md
md file toegevoegd met link naar lab1 opdracht uit eigen portfolio.
> Lab1 opdracht - Madina Jurakholova

- Yaiza_NarganezGomez.md
Added personal portfolio link into .md file
> Adding personal link to portfolio

- Britt_VanDerLinden.md
> added lab 2

- madina_jurakholova.md
There you can find an md file named note_todo with the link of codepen. With this I hope I achieved my lab3 skill.
> Updated my md file to English and I added a link to my lab3 exercice

- timothy_koenig.md
opmerking:
in de codepen zal je "in ABC" zien staan. Dit is een feature waarvoor ik met een aparte API wilde werken om de geolocatie om te zetten naar een stad/provincie om weer te geven. Dit werkte in mijn code alleen wil deze niet op codepen werken (maar het werkt dus wel in de code in mijn github portfolio) dus heb ik de plaats waar ik deze code oproep dan maar in comment gezet in de codepen.
> added lab4

- timothy_koenig.md
codepen version without mongoDB
code in repository with mongoDB
> added lab 5

- madina_jurakholova.md
In the md file in heading lab5, you can find 3 links:
- Link to my folder lab5 in my portfolio repository
- Link to the repository of my lab5 message API where you can find all my commits
- Link to codepen
> Added a link to my lab 5 repository and codepen

- Jasper_Peeters.md
Lab 4 is now added in Portfolio
> Added lab 4 

- Miguel_Lammens.md
Ik heb de functies _saveToStorage_, _removeFromStorage_ en _loadFromStorage_ herschreven omdat de filter methode het niet goed deed.
Nu zou het wel deftig moeten werken.
> bug fixed week3 + MongoDB

- bryan_vanmechelen.md
> Lab 4 completed and M001: MongoDB Basics 

- madina_jurakholova.md
Finished my lab6 exercise. Updates are sent to MongoDB database and in the md file you can find a recorded gif and links to my repositories and to my app.
> Lab6 finished

- Stefan_Mladjenovic.md
Added Stefan_Mladjenovic.md with the link to my portfolio repository
> Added Stefan_Mladjenovic.md

- Seppe_Vangeel.MD
> Lab 1 is finished

- Seppe_Bellens.md
Click on the link to go to my project.
In this project you can find my verification and the link to the website.
> added Link to lab1

- Stijn_Bouckaert.md
You can find the screenshots in the "lab2 - grid" folder on my portfolio.
I've also added a link to codepen there.
> added lab2

- Jonathan_Verhaegen.md
Bij lab1 staat er ook een betere screenshot van git-it
> added lab2 to portfolio & retry git-it screenshot

- stephanie_lambrighs.md
- Updated the links to my labs
- Added lab 2
> Adding lab 2

- Brian_Cautaerts.md
Finished all excercises from Lab2: CSS layout & flexbox
> Added lab2 to portfolio

- Gunnar_VanRemoortere.md
Lab 2 afgewerkt, links met solutions naar codepen zijn in de md file toegevoegd. De rest (screenshots) is te vinden op mijn portfolio via de portfolio link onder de map lab2.
> Gunnar Van Remoortere LAB2 Pull Request

- Stefan_Mladjenovic.md
This time it should be correct, I deleted the previous fork and made the .md file again and individually added it.
> Properly updated .md file and made it ready for pull request

- stephanie_lambrighs.md
lab 3: inlevering portfolio url
> added lab 3 url

- Silke_Rondas.md
> Lab 2 added

- Seppe_Vangeel.MD
> Added link to lab 3

- Brian_Cautaerts.md
Hello Joris
Please checkout my lab 3 excercise 🙂
> Added lab 3 to markdown file

- bob_storms.md
You can find the link to Codesandbox in the README of the repo.
> Added link to Lab 4

- Jonathan_Verhaegen.md
> added lab3 future proof js

- Nick_Bevers.md
> Added lab 4 repo to my file as well as the codesandbox which contains the sandbox link

- Ward_Vanelverdinghe.md
Labo 2 voltooid
Labo 3 voltooid
> Added link to labo's 

- Jonathan_Verhaegen.md
> added lab4 - api

- Stijn_Bouckaert.md
I added the link to our third assignment
> added third assignment

- Sarah_Oorts.md
In de codesandbox code, doet de browser test het niet maar via deze link van codesandbox wel: https://5zde3.csb.app/
> updated Sarah_Oorts.md with lab 4 github link

- Silke_Rondas.md
> Lab 3 added

- Stefan_Mladjenovic.md
Yo Joris
Forked latest version and updated my .md file.
With Brian Cautaerts' guidance, hopefully it works now.
Stefan
> Added lab 3 and 4 to .md file.

- Aaron_Claes.md
Mijn code voor lab 5 staat in mijn portfolio repo, maar ik heb deze code ook in een nieuwe repo moeten plaatsen om deze met Heroku te kunnen deployen. 
Heroku laat het namelijk niet toe om een nodejs project te deployen dat niet in de root folder zit. 
De link naar de gehoste repo staat in de readme.
> Added Lab 5 to Aaron_Claes.md

- Glenn_VanLaere.md
lab 4 volledig werkend met localstorage/ reclame gebouwd voor schoolproject vorig jaar
> lab 4 added

- Brian_Cautaerts.md
Hey Joris
Lab 4 is toegevoegd aan mijn portfolio, kan je deze controleren alsjeblieft?
In app.js -> line 4 staat een functie die een string omzet naar een md5 hash, deze had ik nodig om met de marvel api te verbinden. Ik heb wat gegoogled en zag dat er in javascript geen md5() functie is zoals in php.
Ik heb geprobeerd om met CryptoJS cdn te werken maar dit werkte niet vandaar dat ik gewoon deze functie gecopypaste heb van het internet.
Alvast bedankt!
> added lab4 to portfolio

- robbe_huybrechts.md
Lab 4 en 5 wordt nog aan gewerkt, maar hier is mijn sockets-applicatie alvast!
> Link naar Lab 6 toegevoegd

- bob_storms.md
De commit history vind je in de map van "Lab6 - Web Sockets" zelf. Om te deployen naar Heroku, heb ik een aparte repo aangemaakt met identieke code uit die map.
> docs: add lab 6

- Glenn_VanLaere.md
1 raar voorval is dat bij de tester ik cors-anywhere voor mijn api moest steken. (maar het werkt wel!)
> lab5 added

- Seppe_Vangeel.MD
Finished lab 5
Everything worked on Postman (& browser)
The codepen didn't... I can't find the reason or the issue
> Add link to lab 5

- Flor_VanKuyk.md
A finished Lab 4 with link to codepen!
> Added Lab 4
